name: MLflow Stage Deploy

on:
  repository_dispatch:
    types:
      - mlflow-staging-deploy
      - mlflow-prod-deploy

jobs:
  test-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Print payload
        run: |
          echo "Model: ${{ github.event.client_payload.model_name }}"
          echo "Version: ${{ github.event.client_payload.version }}"
          echo "Stage: ${{ github.event.client_payload.stage }}"
