name: MLOps PROD Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    environment:
      name: prod

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      # 1️⃣ Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Mensagem inicial
      - name: Start
        run: echo "🚀 Starting PROD deployment..."

      # 3️⃣ Configura Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 4️⃣ Instala dependências Python
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5️⃣ Promove modelo
      - name: Promote model
        run: python src/deployment/promote_model.py

      # 6️⃣ Configura credenciais AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 7️⃣ Login no ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-2 | \
          docker login --username AWS --password-stdin 494722910828.dkr.ecr.us-east-2.amazonaws.com

      # 8️⃣ Build e push Docker para ECR
      - name: Build and Push Docker Image
        run: |
          docker build -t iris-api ./serving/api
          docker tag iris-api:latest 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest
          docker push 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest

      # 9️⃣ Deploy Kubernetes
      - name: Deploy Kubernetes
        run: kubectl apply -f infra/kubernetes/prod/

      # 🔟 Mensagem final
      - name: Finish
        run: echo "✅ Production deployed"
